### ISSUE TITLE
Get next.js app to build on vercel

### ISSUE THREAD

**Issue by mpaler** [ctw3dao/ctw3#1]
Just can't get a vanilla next.js app to build. :(

https://vercel.com/ethereum-tag-service/ctw3/F4SbTDbbqVDe4S5BixgXgM9Sejyd

```
.../node_modules/secp256k1 install$ node-gyp-build \|\| exit 0
--
12:00:33.137 | .../keytar@7.3.0/node_modules/keytar install: prebuild-install WARN install libsecret-1.so.0: cannot open shared object file: No such file or directory
12:00:33.360 | .../node_modules/secp256k1 install: Done
```

**Comment by zawilliams** [comment]
Ok, so finally figured this one out.

The issue is with... drumroll: `hardhat-ethernal`

If you run `pnpm why prebuild-install` it'll give you:

```bash
devDependencies:
hardhat-ethernal 0.7.1
└─┬ keytar 7.3.0
  └── prebuild-install 6.1.4
```

I thought it was a dependency issue, and technically it is, but I updated Vercel's install command to skip the `@ctw3/contracts` package using `pnpm install --filter=!@ctw3/contracts` and that fixed things.

Back in bizzz.
